### ISSUE TITLE
memory issues for non-sparse transition matrix

### ISSUE THREAD

**Issue by idc9** [gvanderheide/discreteMarkovChain#11]
I found this package super helpful for my research! There is an issue when the transition matrix is not sparse.

**Issue**
`markovChain` assumes that `P` is sparse. If `P` is not sparse (e.g. PageRank) using a sparse implementation leads to a memory explosion (and much slower code). 

**Solution**
- allow the use to choose if `P` is sparse or dense
- write versions of the eigen-solvers that handle numpy arrays (should be mostly copy and paste)

**Comment by gvanderheide** [comment]
Thanks. 

Can you perhaps give a code example where this problem occurs? I'm not sure how a conversion to a sparse matrix leads to a memory explosion. Does this problem occur with a specific solver or with all of them?

**Comment by gvanderheide** [comment]
Ok. It indeed seems that the conversion to a sparse matrix increases memory. The matrix D below uses about 800mb of memory. After I delete the original P the memory consumption is about 1.2 Gb. During the conversion there can be spikes of about 4gb. I see how that can be troubling. 

    import numpy as np
    from scipy.sparse import csr_matrix

    n = 10000
    D = np.ones((n,n),dtype=float)*1./n
    P = csr_matrix(D)
    del D

I still have to think a little bit how to fix it. I'm using methods from scipy.sparse for which there are no good dense alternatives, such as the gmres solver and checking connected components of a graph. 

I'm not smart enough to implement (efficient) dense versions of such methods myself, so such a change would break compatibility.
